INSERT INTO transactions (
    hash, txid, wtxid, withash, tx_hex,
    "index", block_hash, block_number, block_timestamp,
    lock_time, size, virtual_size, discount_virtual_size,
    version, is_coinbase,
    input_count, output_count, input_value, output_value, fee,
    node_fee,
    inputs, outputs,
    weight, discount_weight, sigops
) VALUES (
    :hash, :txid, :wtxid, :withash, :tx_hex,
    :index, :block_hash, :block_number, :block_timestamp,
    :lock_time, :size, :virtual_size, :discount_virtual_size,
    :version, :is_coinbase,
    :input_count, :output_count, :input_value, :output_value, :fee,
    :node_fee,
    :inputs, :outputs,
    :weight, :discount_weight, :sigops
)
ON CONFLICT(hash, "index") DO UPDATE SET
    txid=excluded.txid,
    wtxid=excluded.wtxid,
    withash=excluded.withash,
    tx_hex=excluded.tx_hex,
    block_hash=excluded.block_hash,
    block_number=excluded.block_number,
    block_timestamp=excluded.block_timestamp,
    lock_time=excluded.lock_time,
    size=excluded.size,
    virtual_size=excluded.virtual_size,
    discount_virtual_size=excluded.discount_virtual_size,
    version=excluded.version,
    is_coinbase=excluded.is_coinbase,
    input_count=excluded.input_count,
    output_count=excluded.output_count,
    input_value=excluded.input_value,
    output_value=excluded.output_value,
    fee=excluded.fee,
    node_fee=excluded.node_fee,
    inputs=excluded.inputs,
    outputs=excluded.outputs,
    weight=excluded.weight,
    discount_weight=excluded.discount_weight,
    sigops=excluded.sigops
