CREATE TABLE IF NOT EXISTS blocks (
    hash TEXT PRIMARY KEY,
    number INTEGER,
    timestamp INTEGER,
    median_time INTEGER,
    confirmations INTEGER,
    size INTEGER,
    stripped_size INTEGER,
    weight INTEGER,
    version INTEGER,
    version_hex TEXT,
    merkle_root TEXT,
    nonce INTEGER,
    bits TEXT,
    previous_block_hash TEXT,
    next_block_hash TEXT,
    transaction_count INTEGER,
    signblock_challenge TEXT,
    signblock_witness_asm TEXT,
    signblock_witness_hex TEXT
);

CREATE TABLE IF NOT EXISTS transactions (
    hash TEXT,
    txid TEXT,
    wtxid TEXT,
    withash TEXT,
    tx_hex TEXT,
    "index" INTEGER,
    block_hash TEXT,
    block_number INTEGER,
    block_timestamp INTEGER,
    lock_time INTEGER,
    size INTEGER,
    virtual_size INTEGER,
    discount_virtual_size REAL,
    weight INTEGER,
    discount_weight INTEGER,
    sigops INTEGER,
    version INTEGER,
    is_coinbase INTEGER,
    input_count INTEGER,
    output_count INTEGER,
    input_value TEXT,
    output_value TEXT,
    fee TEXT,
    node_fee TEXT,
    inputs TEXT,
    outputs TEXT,
    PRIMARY KEY (hash, "index")
);
