CREATE TABLE IF NOT EXISTS blocks (
    hash TEXT PRIMARY KEY,
    height BIGINT,
    version BIGINT,
    prev_block_hash TEXT,
    next_block_hash TEXT,
    merkle_root TEXT,
    time BIGINT,
    median_time BIGINT,
    tx_count BIGINT,
    size BIGINT,
    stripped_size BIGINT,
    weight BIGINT,
    signblock_solution_hex TEXT,
    txids JSONB
);

CREATE TABLE IF NOT EXISTS transactions (
    txid TEXT PRIMARY KEY,
    wtxid TEXT,
    hash TEXT,
    withash TEXT,
    block_hash TEXT,
    block_height BIGINT,
    block_time BIGINT,
    tx_index_in_block INTEGER,
    confirmed BOOLEAN,
    version BIGINT,
    lock_time BIGINT,
    size BIGINT,
    vsize DOUBLE PRECISION,
    weight BIGINT,
    discount_vsize DOUBLE PRECISION,
    discount_weight BIGINT,
    vin_count INTEGER,
    vout_count INTEGER,
    fee_by_asset JSONB,
    explicit_in_by_asset JSONB,
    explicit_out_by_asset JSONB,
    has_any_confidential BOOLEAN,
    has_pegin BOOLEAN,
    has_issuance BOOLEAN
);

CREATE TABLE IF NOT EXISTS txins (
    txid TEXT NOT NULL,
    vin INTEGER NOT NULL,
    prev_txid TEXT,
    prev_vout INTEGER,
    sequence BIGINT,
    is_coinbase BOOLEAN,
    scriptsig_hex TEXT,
    scriptsig_asm TEXT,
    txinwitness JSONB,
    pegin_witness JSONB,
    is_pegin BOOLEAN,
    has_issuance BOOLEAN,
    issuance_asset_blinding_nonce TEXT,
    issuance_asset_entropy TEXT,
    issuance_amount BIGINT,
    issuance_inflation_keys BIGINT,
    prevout_scriptpubkey_hex TEXT,
    prevout_script_type TEXT,
    prevout_address TEXT,
    PRIMARY KEY (txid, vin)
);

CREATE TABLE IF NOT EXISTS txouts (
    txid TEXT NOT NULL,
    vout INTEGER NOT NULL,
    asset_id TEXT,
    asset_commitment TEXT,
    value_sat BIGINT,
    value_commitment TEXT,
    scriptpubkey_hex TEXT,
    scriptpubkey_asm TEXT,
    script_type TEXT,
    address TEXT,
    is_op_return BOOLEAN,
    op_return_data_hex TEXT,
    is_fee BOOLEAN,
    surjection_proof TEXT,
    PRIMARY KEY (txid, vout)
);
