"""Schema hints for NDJSON outputs.

These are best-effort keys populated by normalization.
"""

BLOCK_SCHEMA_KEYS = [
    "hash",
    "confirmations",
    "size",
    "stripped_size",
    "weight",
    "number",
    "version",
    "version_hex",
    "merkle_root",
    "timestamp",
    "median_time",
    "nonce",
    "bits",
    "previous_block_hash",
    "next_block_hash",
    "transaction_count",
    "signblock_challenge",
    "signblock_witness_asm",
    "signblock_witness_hex",
]

TRANSACTION_SCHEMA_KEYS = [
    "hash",
    "txid",
    "wtxid",
    "withash",
    "tx_hex",
    "size",
    "virtual_size",
    "discount_virtual_size",
    "weight",
    "discount_weight",
    "sigops",
    "version",
    "lock_time",
    "block_number",
    "block_hash",
    "block_timestamp",
    "is_coinbase",
    "index",
    "inputs",
    "outputs",
    "input_count",
    "output_count",
    "input_value",
    "output_value",
    "fee",
    "node_fee",
]
